### ISSUE TITLE
First pass at datasets and data loaders

### ISSUE THREAD

**Issue by darsnack** [FluxML/FastAI.jl#1]
Implement [PyTorch's Dataloader interface](https://pytorch.org/docs/stable/data.html?highlight=dataloader#module-torch.utils.data).

Highlighted features:
- [x] Support for map-style and iterable-style datasets
- [ ] Custom data loading order
- [ ] Automatic batching
    - [ ] Sampling
- [ ] Multi-process loading
- [ ] Memory pinning (for better GPU support)

----

Copied over from the ML tracker issue. @opus111 feel free to edit.

**Comment by jph00** [comment]
I'd suggest implementing fastai2's DataLoader since it's built on the same foundation but much more flexible, and is needed for much of the high level functionality.
http://dev.fast.ai/data.load
