### ISSUE TITLE
N-dimensional CNN models

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/FastAI.jl#137]
fastai has this already for certain models to support audio and time series processing. We should be able to do that but even better, because Flux's Conv and Pooling layers can (theoretically) handle an arbitrary number of dimensions.

**Comment by lorenzoh** [comment]
Yeah, it's just a matter of adding models now which take in 3D images. Projections and augmentations work on N-D images, masks, keypoints already; so does one-hot encoding N-D masks.

**Comment by ToucheSir** [comment]
Totally forgot I'd opened this issue! What do you think about an `ndim` parameter or something similar for XResNets and U-Nets to pass through to `convx`? Then instead of `(ks, ks)` on https://github.com/FluxML/FastAI.jl/blob/master/src/models/xresnet.jl#L5, you'd have `ntuple(_ -> ks, ndim)` (or maybe `ntuple(Returns(ks), ndim)` on 1.7+).

**Comment by lorenzoh** [comment]
Sounds like a good idea! I guess pooling layers would have to take that in as well 🤔

**Comment by lorenzoh** [comment]
See #181
