### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by rishabhvarshney14** [FluxML/FastAI.jl#15]
I am really interested in this project and want to contribute but currently, I am not sure how this project is planned. Is there any way if I can help?

**Comment by AriMKatz** [comment]
Hi, thanks for stopping by. There's a lot to work on. What's your experience and what sort of things are you interested in working on? (General ml infra, NLP, cv etc)

**Comment by rishabhvarshney14** [comment]
I am new to both open-source and Julia. As of my interests I am interested in Computer Vision and Reinforcement Learing but I am just starting out in this field and looking to learn more.

**Comment by darsnack** [comment]
We're working on putting up a more formal contributions guide, but many of our members are a little swamped right  now with end of the year deadlines.

The purpose of this repo is to provide a similar API to fast-ai from Python by wrapping the repos listed on the README.md. At this stage, there isn't a good list of sub-steps to achieving that goal, but the contribution guide will help with that. If you are more familiar with fast-ai, then you could open some issues on the repo to help flesh out our future direction.
