### ISSUE TITLE
Makie crashes precompilation

### ISSUE THREAD

**Issue by Oblynx** [FluxML/FastAI.jl#156]
This looks like a Makie bug affecting FastAI.

I try to precompile FastAI, but it segfaults:
```julia
(FastAI) pkg> status
      Status `~/tmp/FastAI/Project.toml`
  [5d0beca9] FastAI v0.1.0

julia> using FastAI
[ Info: Precompiling FastAI [5d0beca9-ade8-49ae-ad0b-a3cf890e669f]
WARNING: Method definition Type##kw(Any, Type{Base.MPFR.BigFloat}, Base.Irrational{:log4π}) in module IrrationalConstants at irrationals.jl:180 overwritten in module LogExpFunctions on the same line (check for duplicate calls to `include`).
  ** incremental compilation may be fatally broken for this module **
...
signal (11): Segmentation fault
in expression starting at ~/.julia/packages/FastAI/4mXj2/src/FastAI.jl:11
```

The [line which panics](https://github.com/FluxML/FastAI.jl/blob/master/src/FastAI.jl#L11): `using Makie`

I confirm the same error when using only Makie:
```julia
(FastAI) pkg> status
      Status `~/tmp/FastAI/Project.toml`
  [ee78f7c6] Makie v0.15.0

julia> using Makie

signal (11): Segmentation fault
```

Can anybody else reproduce with this version of Makie?

**Comment by lorenzoh** [comment]
Have you opened an issue on the Makie.jl repo?

**Comment by Oblynx** [comment]
> Have you opened an issue on the Makie.jl repo?

done, thanks!

And thank you so much for a great package, I look forward to using this!

**Comment by lorenzoh** [comment]
Thanks! Closing this for now, as it seems related to Makie.jl
