### ISSUE TITLE
Visualization functions are not working

### ISSUE THREAD

**Issue by kpauly** [FluxML/FastAI.jl#184]
It appears as if the visualization functions provided under interpretation/method.jl don't come into scope. 

When following the tutorial under keypoint regression, when I do: `julia> showbatch(method, (xs, ys))`
I get:
```
ERROR: UndefVarError: showbatch not defined
Stacktrace:
 [1] top-level scope
   @ REPL[27]:1
```
This happens for every show... function in method.jl. Using more explicit importing or namespace syntax doens't seem to help.
I'm on Windows 10 and working in VS CODE 1.62.3 (Julia extension v1.5.6). Currently Julia v1.7.0 but the issue arose in 1.6.x as well. I also get the issue when working in a Pluto.jl notebook.

```
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 14
```
```
pkg> status
  [336ed68f] CSV v0.8.5
  [052768ef] CUDA v3.5.0
  [13f3f980] CairoMakie v0.6.6
  [5d0beca9] FastAI v0.2.0
  [916415d5] Images v0.24.1
  [ee78f7c6] Makie v0.15.3
  [90137ffa] StaticArrays v1.2.13
  [bd369af6] Tables v1.6.0
```

**Comment by lorenzoh** [comment]
These are not in the latest release (v0.2.0) but should work on the master branch (add by using `]add FastAI#master`). I'll try make a new release soon to alleviate the confusion! Thanks for the report

**Comment by kpauly** [comment]
Oh, thanks for the swift clarification! I can confirm that it works using the master branch.

**Comment by lorenzoh** [comment]
0.3.0 is now released by the way!
