### ISSUE TITLE
Tutorial errors out

### ISSUE THREAD

**Issue by dave7895** [FluxML/FastAI.jl#19]
The [tutorial to train a model from scratch](https://fluxml.ai/FastAI.jl/dev/docs/notebooks/fitonecycle.ipynb.html) errors out and complains about a wrong keyword argument:

```julia
DataLoader(::Any, ::Any; collate, buffered, partial, useprimary) at ~\.julia\packages\DataLoaders\uGlPg\src\DataLoaders.jl:54 got unsupported keyword argument "validbsfactor"
DataLoader(::Any) at ~\.julia\packages\DataLoaders\uGlPg\src\DataLoaders.jl:54 got unsupported keyword argument "validbsfactor"
```

I followed the stack trace to DLPipelines.jl and DataLoaders.jl and can't find `validbsfactor` anywhere. What does it do?

**Comment by dave7895** [comment]
PR in preparation to fix

**Comment by lorenzoh** [comment]
Solved by the release of DLPipelines.jl v0.2.0
