### ISSUE TITLE
Functions `getcoltypes` and `gettransformdict` are not exported properly

### ISSUE THREAD

**Issue by ShuhuaGao** [FluxML/FastAI.jl#210]
When following the [Tabular Classification](https://fluxml.ai/FastAI.jl/dev/notebooks/tabularclassification.ipynb.html) tutorial, I encountered the following error: `UndefVarError: getcoltypes not defined`.

The reason is that these symbols are not exported in "Tabular.jl" and thus not exported by FastAI through `@reexport using .Tabular`.

I can make a PR. However, I am not clear about your original intention. Do you want `FastAI.getcoltypes` or `Tabular.getcoltypes`? The latter works now without changing the source code.

**Comment by lorenzoh** [comment]
The later version with `FastAI` prefix should be in the docs. Thanks for reporting! Ill keep this open until I fix the docs

**Comment by ShuhuaGao** [comment]
Did you mean `FastAI.getcoltypes` is the prefered one? I will also try to make a PR along with my learning of FastAI.jl. Thanks for the excellent work.

**Comment by lorenzoh** [comment]
`Tabular.getcoltypes` should be used is what I meant 👍 happy to review a PR

**Comment by lorenzoh** [comment]
Notebook has been updated, so closing this
