### ISSUE TITLE
Documentation link broken for `Custom Learning tasks`

### ISSUE THREAD

**Issue by Karthik-d-k** [FluxML/FastAI.jl#220]
I was going through the documentation of `FastAi.jl` and i found out `Custom Learning tasks` page is broken.
Looks like it should point to https://fluxml.ai/FastAI.jl/dev/docs/learning_methods.md.html, which works perfectly fine.
Currently it is pointing to https://fluxml.ai/FastAI.jl/dev/docs/learning_tasks.md.html which seems to be not correct.

**Comment by lorenzoh** [comment]
Are you using the new documentation system? The docs are in the process of being moved and some old pages still remain. Can you try this link: https://fluxml.ai/FastAI.jl/dev/documents/docs/learning_methods.md/ and let me know if it works?
