### ISSUE TITLE
Docs aren't working correctly.

### ISSUE THREAD

**Issue by Chandu-4444** [FluxML/FastAI.jl#237]
Visiting this page: https://fluxml.ai/FastAI.jl/dev/documents/README.md and clicking on one of the links from the Example code snippet isn't opening the tab but the URL is getting changed.

**Comment by lorenzoh** [comment]
Should be fixed after rebuilding the docs, I just triggered the workflow 👍

**Comment by lorenzoh** [comment]
Fixed now
