### ISSUE TITLE
`Quickstart` tutorial no longer works (`loaddataset` doesn't exist)

### ISSUE THREAD

**Issue by claforte** [FluxML/FastAI.jl#254]
Hi, this code from `https://fluxml.ai/FastAI.jl/dev/documents/notebooks/quickstart.ipynb` fails with the latest FastAI.jl release:
```julia
using FastAI
data, blocks = loaddataset("imagenette2-320", (Image, Label))
task = ImageClassificationSingle(blocks, size=(256, 256))
learner = tasklearner(task, data, callbacks=[ToGPU(), Metrics(accuracy)])
fitonecycle!(learner, 5, 0.033)
```

with `UndefVarError: loadddataset not defined`.
If I replace the 2nd line with `data, blocks = load(datarecipes()["imagenette2-320"])` (from an earlier page in the docs), it works.

**Comment by lorenzoh** [comment]
Hi Christian, thanks for reporting this! 

I think there’s been an issue with the documentation build, as this should be fixed in the docs source on master (see https://github.com/FluxML/FastAI.jl/blob/master/docs/notebooks/quickstart.ipynb).

I’ll leave this open until I get around to releasing 0.5 and  subpackages which will be breaking (#240).

**Comment by claforte** [comment]
Ok, in the meantime I tried to `] dev FastAI` with the latest Master branch, but I can't even get `using FastVision` to work... i.e. the notebook you linked to doesn't work for me. I'm not familiar with subpackages... is there something special I need to do, to add FastVision and other subpackages, before you officially register them?

**Comment by claforte** [comment]
BTW it would be great if there was an easy way to read the previous FastAI.jl documentation... right now it only points to the `dev` version, instead of the latest version that you registered... (... that presumably is more tested/stable?)

Sorry to bother you during your vacations, I'm just a bit disappointed I'll have to revert to just using Lux or Flux without your neat high-level libraries. ;-)

**Comment by claforte** [comment]
Nevermind! This older code works with FastAI.jl v0.4.3:
```julia
# Adapted from https://fluxml.ai/FastAI.jl/dev/documents%2Fnotebooks%2Fquickstart.ipynb
using FastAI
using Metalhead

import CairoMakie
CairoMakie.activate!(type="png")

data, blocks = loaddataset("imagenette2-320", (Image, Label))

image,class = sample = getobs(data, 1000)
@show class
image

task = ImageClassificationSingle(blocks, size=(256,256)) # task = ImageClassificationSingle(blocks, size=(256, 256))
learner = tasklearner(task, data, callbacks=[ToGPU(), Metrics(accuracy)], backbone=ResNet(34).layers[1:end-1])
fitonecycle!(learner, 10)
showoutputs(task, learner)
```
![image](https://user-images.githubusercontent.com/5090329/183771998-76fb97ee-a57e-4db0-a397-000a879301fe.png)

Thanks!

**Comment by lorenzoh** [comment]
Sorry about this! I didn't want to make a big release right before my absence and me adding versioning support to Pollen.jl is still WIP which created this confusing situation where only the dev docs are shown. I'll leave this open until proper versioning of the documentation is added. Thanks for bearing with that!

**Comment by lorenzoh** [comment]
FastAI.jl 0.5 and the subpackages have been released now, along with up-to-date documentation, so I am closing this. Let me know if something is still not working!
