### ISSUE TITLE
Use case: Siamese networks for image similarity

### ISSUE THREAD

**Issue by lorenzoh** [FluxML/FastAI.jl#31]
Porting fastai's tutorial (https://docs.fast.ai/tutorial.siamese.html) that shows how to use the mid-level APIs to solve a custom task.

**Comment by ToucheSir** [comment]
Do we want to explore contrastive losses (e.g. triplet loss) as part of this too? Fastai has a big gap there, so having support in Julia land would be great :)

**Comment by lorenzoh** [comment]
Not that familiar with them, but that would be great!

**Comment by lorenzoh** [comment]
Can be seen at https://fluxml.ai/FastAI.jl/dev/notebooks/siamese.ipynb.html
