### ISSUE TITLE
Some maintenance and housekeeping things

### ISSUE THREAD

**Issue by DhairyaLGandhi** [FluxML/FastAI.jl#9]
We should do a full code review, so the package matches the Flux code style and approach a bit better. There are also several places that need cleanup with having logging statements still around.

**Comment by opus111** [comment]
Absolutely agree.  Code was never meant to be shared beyond the immediate team.  Names and comments are a mix of my style and the original Python code.  Needs to be consistent.  Open to all suggestions and standards.

**Comment by darsnack** [comment]
Yeah was planning on doing a clean-up pass after making sure the CI/docs are working. Many of the "comment" strings are now converted to docstrings which cleaned up a lot.
